name: Sapphire Tests
on: [push]
jobs:
  SapphireTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        with:
          node-version: 20
    - name: Install cppcheck
      run: sudo apt install -y cppcheck
    - name: Sapphire unit tests
      run: cd util && ./runtests GitHubActions
